Repository pstage-ocr-team6/ocr-teamcode, pull requests merged in 2021-06, with the labels that each got.

#22 [#21] Add preprocessed binary images
  custom_augment.py
  pre_processing.py
  train.py
Labels: enhancement

#36 [#35] Improve readability.
  custom_augment.py
  data_tools/download.sh
  data_tools/make_dataset.py
  inference.py
  networks/SATRN.py
  networks/loss.py
  pre_processing.py
  requirements.txt
  submission.txt
  train.py
  utils.py
Labels: documentation

#38 [#37] Add comments
  checkpoint.py
  custom_augment.py
  data_tools/extract_tokens.py
  data_tools/make_dataset.py
  data_tools/parse_upstage.py
  data_tools/train_test_split.py
  dataset.py
  inference.py
  metrics.py
  networks/SATRN.py
  networks/loss.py
  pre_processing.py
  scheduler.py
  train.py
  transform.py
  utils.py
Labels: documentation

#40 [#18] Update README.md
  README.md
  assets/competition-overview.png
  assets/demo.png
  assets/logo.png
  exp/nb_SparseImageWarp.py
  requirements.txt
  submit/output.csv
Labels: documentation

#41 [#18] Change demo image and fix typo
  README.md
  assets/demo.png
Labels: documentation

#43 [#42] Add documentation for model description
  assets/Attention.png
  assets/SATRN.png
  assets/SATRN_feedforward.png
  networks/README.md
Labels: documentation

#44 [#42-fix] Fix image on model description page
  networks/README.md
Labels: bug, documentation
